#!/usr/bin/env python3
"""
Agent Skill: Invoice Generator
Gold Tier - Generate invoices from templates
"""

import os
import sys
import json
from datetime import datetime
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))


class InvoiceGenerator:
    """Generate professional invoices"""
    
    def __init__(self):
        self.invoice_dir = Path(__file__).parent.parent / "Invoices"
        self.invoice_dir.mkdir(parents=True, exist_ok=True)
        self.template = self._load_template()
    
    def _load_template(self):
        """Load invoice template"""
        return {
            "company_name": "AI Employee Services",
            "company_address": "123 Business St, City, Country",
            "company_email": "billing@aiemployee.com",
            "company_phone": "+1-234-567-8900",
            "currency": "USD",
            "payment_terms": "Net 30",
            "bank_details": {
                "bank_name": "Business Bank",
                "account_number": "1234567890",
                "routing_number": "987654321"
            }
        }
    
    def generate_invoice(self, client_name: str, client_email: str, 
                        description: str, amount: float, 
                        invoice_number: str = None) -> dict:
        """
        Generate an invoice
        
        Args:
            client_name: Client name
            client_email: Client email
            description: Service description
            amount: Invoice amount
            invoice_number: Optional invoice number (auto-generated if not provided)
        
        Returns:
            dict: Invoice details and file path
        """
        # Generate invoice number if not provided
        if not invoice_number:
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            invoice_number = f"INV-{timestamp}"
        
        # Calculate amounts
        subtotal = amount
        tax_rate = 0.0  # Adjust as needed
        tax = subtotal * tax_rate
        total = subtotal + tax
        
        # Dates
        today = datetime.now()
        due_date = datetime(today.year, today.month + 1, today.day)
        
        # Create invoice content
        invoice_content = f"""# INVOICE

**Invoice Number:** {invoice_number}  
**Date:** {today.strftime('%Y-%m-%d')}  
**Due Date:** {due_date.strftime('%Y-%m-%d')}

---

## From

**{self.template['company_name']}**  
{self.template['company_address']}  
Email: {self.template['company_email']}  
Phone: {self.template['company_phone']}

---

## To

**{client_name}**  
Email: {client_email}

---

## Invoice Details

| Description | Amount |
|-------------|--------|
| {description} | ${subtotal:,.2f} |

---

## Summary

| | |
|---|---|
| **Subtotal:** | ${subtotal:,.2f} |
| **Tax ({tax_rate*100}%):** | ${tax:,.2f} |
| **Total:** | **${total:,.2f}** |

---

## Payment Information

**Payment Terms:** {self.template['payment_terms']}  
**Bank Name:** {self.template['bank_details']['bank_name']}  
**Account Number:** {self.template['bank_details']['account_number']}  
**Routing Number:** {self.template['bank_details']['routing_number']}

---

## Notes

Thank you for your business!  
Please make payment by the due date.

---

*Generated by AI Employee Invoice System*
"""
        
        # Save invoice
        filename = f"{invoice_number}_{client_name.replace(' ', '_')}.md"
        filepath = self.invoice_dir / filename
        filepath.write_text(invoice_content, encoding='utf-8')
        
        # Save invoice metadata
        metadata = {
            "invoice_number": invoice_number,
            "client_name": client_name,
            "client_email": client_email,
            "description": description,
            "amount": amount,
            "tax": tax,
            "total": total,
            "date": today.isoformat(),
            "due_date": due_date.isoformat(),
            "status": "pending",
            "file_path": str(filepath)
        }
        
        metadata_file = self.invoice_dir / f"{invoice_number}_metadata.json"
        with open(metadata_file, 'w') as f:
            json.dump(metadata, f, indent=2)
        
        return {
            "success": True,
            "invoice_number": invoice_number,
            "file_path": str(filepath),
            "metadata_path": str(metadata_file),
            "total": total,
            "due_date": due_date.strftime('%Y-%m-%d')
        }


if __name__ == '__main__':
    # Test invoice generation
    generator = InvoiceGenerator()
    
    result = generator.generate_invoice(
        client_name="Test Client",
        client_email="test@example.com",
        description="AI Services - January 2026",
        amount=500.00
    )
    
    print("Invoice generated!")
    print(f"Invoice Number: {result['invoice_number']}")
    print(f"Total: ${result['total']}")
    print(f"File: {result['file_path']}")
