#!/usr/bin/env python3
"""
LinkedIn Manager - Combined manager for posting and watching.
Provides a unified interface for all LinkedIn automation tasks.
"""

import os
import sys
import time
import random
import logging
import argparse
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv
from playwright.sync_api import sync_playwright

# Load environment variables
load_dotenv()

# Check Python version
if sys.version_info < (3, 13):
    print(f"Error: Python 3.13 or higher is required. Current version: {sys.version}")
    sys.exit(1)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

# Configuration
LINKEDIN_EMAIL = os.getenv("LINKEDIN_EMAIL", "sehrkhan873@gmail.com")
LINKEDIN_PASSWORD = os.getenv("LINKEDIN_PASSWORD", "")
USER_DATA_DIR = "./linkedin_session"
VAULT_PATH = "./Inbox"
ERROR_SCREENSHOT = "linkedin_error.png"
POLL_INTERVAL = 60  # seconds
MAX_RETRIES = 3
HEADLESS = True

# Ensure directories exist
Path(VAULT_PATH).mkdir(parents=True, exist_ok=True)
Path(USER_DATA_DIR).mkdir(parents=True, exist_ok=True)


def human_like_delay(min_ms=50, max_ms=200):
    """Add human-like delay"""
    time.sleep(random.randint(min_ms, max_ms) / 1000)


def random_mouse_move(page):
    """Perform random mouse movements"""
    try:
        x = random.randint(100, 1200)
        y = random.randint(100, 800)
        page.mouse.move(x, y)
        human_like_delay(100, 300)
    except Exception:
        pass


def save_to_vault(data, message_type="message"):
    """Save LinkedIn data to vault"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{VAULT_PATH}/new_linkedin_{message_type}_{timestamp}.md"

    content = f"""# New LinkedIn {message_type.title()}

**From:** {data.get('sender', 'Unknown')}
**Time:** {data.get('time', 'Unknown')}
**Content:** {data.get('text', 'No content')}

---
*Generated by LinkedIn Manager at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content.strip())

    logging.info(f"Saved to vault: {filename}")
    return filename


def login_to_linkedin(page, email, password):
    """Login to LinkedIn"""
    logging.info("Navigating to LinkedIn login...")
    page.goto("https://www.linkedin.com/login", wait_until="domcontentloaded", timeout=30000)
    human_like_delay(1000, 2000)

    # Check if already logged in
    if "feed" in page.url or "mynetwork" in page.url:
        logging.info("Already logged in")
        return True

    if not password:
        logging.error("No password provided")
        return False

    logging.info("Logging in...")

    try:
        page.fill('input[name="session_key"]', email)
        human_like_delay(500, 1000)
        page.fill('input[name="session_password"]', password)
        human_like_delay(500, 1000)
        page.click('button[type="submit"]')
        human_like_delay(2000, 3000)

        try:
            page.wait_for_url("https://www.linkedin.com/feed/*", timeout=30000)
        except Exception:
            pass

        if "feed" in page.url or "mynetwork" in page.url:
            logging.info("Login successful")
            return True
        else:
            logging.error("Login verification failed")
            return False

    except Exception as e:
        logging.error(f"Login error: {e}")
        return False


def check_new_messages(page):
    """Check for new LinkedIn messages"""
    try:
        page.goto("https://www.linkedin.com/messaging/", wait_until="domcontentloaded", timeout=30000)
        human_like_delay(500, 1000)

        unread_selectors = [
            'li.msg-conversation-listitem--unread',
            '.msg-conversation-card__unread-count',
            '.msg-conversation-card__unread-dot'
        ]

        for selector in unread_selectors:
            try:
                unread_elements = page.locator(selector).all()
                if unread_elements:
                    logging.info(f"Found {len(unread_elements)} unread messages")

                    for element in unread_elements[:3]:
                        try:
                            sender = "Unknown"
                            for s in ['.msg-conversation-card__participant-names', '.msg-conversation-card__title']:
                                try:
                                    sender_elem = element.locator(s).first
                                    if sender_elem.count() > 0:
                                        sender = sender_elem.inner_text(timeout=2000)
                                        break
                                except Exception:
                                    continue

                            text = "No preview available"
                            for t in ['.msg-conversation-card__message-snippet', '.msg-conversation-card__snippet']:
                                try:
                                    text_elem = element.locator(t).first
                                    if text_elem.count() > 0:
                                        text = text_elem.inner_text(timeout=2000)
                                        break
                                except Exception:
                                    continue

                            message_time = "Unknown"
                            for tm in ['.msg-conversation-card__time-stamp']:
                                try:
                                    time_elem = element.locator(tm).first
                                    if time_elem.count() > 0:
                                        message_time = time_elem.inner_text(timeout=2000)
                                        break
                                except Exception:
                                    continue

                            message_data = {
                                'sender': sender.strip(),
                                'text': text.strip(),
                                'time': message_time.strip()
                            }
                            save_to_vault(message_data, "message")

                        except Exception as e:
                            logging.error(f"Error processing message: {e}")
                            continue

                    break
            except Exception:
                continue

    except Exception as e:
        logging.error(f"Error checking messages: {e}")
        raise


def check_new_notifications(page):
    """Check for new LinkedIn notifications"""
    try:
        page.goto("https://www.linkedin.com/notifications/", wait_until="domcontentloaded", timeout=30000)
        human_like_delay(500, 1000)

        unread_selectors = ['.nt-segment--unread', '[data-test-notification-item].nt-segment--unread']

        for selector in unread_selectors:
            try:
                unread_elements = page.locator(selector).all()
                if unread_elements:
                    logging.info(f"Found {len(unread_elements)} unread notifications")

                    for element in unread_elements[:3]:
                        try:
                            text = "No notification text"
                            for t in ['.nt-card__text', '.nt-card__headline']:
                                try:
                                    text_elem = element.locator(t).first
                                    if text_elem.count() > 0:
                                        text = text_elem.inner_text(timeout=2000)
                                        break
                                except Exception:
                                    continue

                            notification_time = "Unknown"
                            for tm in ['.nt-card__time-ago']:
                                try:
                                    time_elem = element.locator(tm).first
                                    if time_elem.count() > 0:
                                        notification_time = time_elem.inner_text(timeout=2000)
                                        break
                                except Exception:
                                    continue

                            notification_data = {
                                'sender': 'LinkedIn Notification',
                                'text': text.strip(),
                                'time': notification_time.strip()
                            }
                            save_to_vault(notification_data, "notification")

                        except Exception as e:
                            logging.error(f"Error processing notification: {e}")
                            continue

                    break
            except Exception:
                continue

    except Exception as e:
        logging.error(f"Error checking notifications: {e}")
        raise


def create_post(page, content):
    """Create and publish a LinkedIn post"""
    try:
        logging.info("Creating LinkedIn post...")

        page.goto("https://www.linkedin.com/feed/", wait_until="domcontentloaded", timeout=30000)
        human_like_delay(1000, 2000)
        random_mouse_move(page)

        # Click on post creation box
        post_start_selectors = ['button[aria-label="Start a post"]', '.share-box-feed-entry__trigger']

        clicked = False
        for selector in post_start_selectors:
            try:
                if page.locator(selector).count() > 0:
                    page.click(selector)
                    human_like_delay(1000, 2000)
                    clicked = True
                    break
            except Exception:
                continue

        if not clicked:
            logging.error("Could not find post creation button")
            return False

        human_like_delay(500, 1000)

        # Enter content
        text_selectors = ['div[contenteditable="true"]', '.ql-editor.textarea']

        for selector in text_selectors:
            try:
                if page.locator(selector).count() > 0:
                    text_elem = page.locator(selector).first
                    text_elem.click()
                    human_like_delay(300, 500)
                    page.keyboard.press('Control+A')
                    human_like_delay(200, 400)
                    page.keyboard.press('Delete')
                    human_like_delay(300, 500)
                    text_elem.type(content, delay=50)
                    human_like_delay(500, 1000)
                    break
            except Exception:
                continue

        human_like_delay(1000, 2000)

        # Click Post button
        post_selectors = ['button:has-text("Post")', 'button:has-text("Post now")']

        for selector in post_selectors:
            try:
                if page.locator(selector).count() > 0:
                    page.click(selector)
                    human_like_delay(2000, 3000)
                    break
            except Exception:
                continue

        human_like_delay(2000, 3000)

        if "feed" in page.url:
            logging.info("Post published successfully!")
            return True
        return True

    except Exception as e:
        logging.error(f"Error creating post: {e}")
        return False


def run_watcher():
    """Run the LinkedIn watcher"""
    logging.info("Starting LinkedIn Watcher...")
    logging.info(f"Email: {LINKEDIN_EMAIL}")
    logging.info(f"Headless: {HEADLESS}")
    logging.info(f"Poll Interval: {POLL_INTERVAL} seconds")

    retries = 0

    while retries < MAX_RETRIES:
        try:
            logging.info(f"Attempt {retries + 1}/{MAX_RETRIES}")

            with sync_playwright() as p:
                browser = p.chromium.launch(
                    headless=HEADLESS,
                    args=[
                        '--disable-blink-features=AutomationControlled',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                        '--disable-setuid-sandbox'
                    ]
                )

                context = browser.new_context(
                    storage_state=USER_DATA_DIR + "/storage_state.json" if os.path.exists(USER_DATA_DIR + "/storage_state.json") else None
                )
                page = context.new_page()

                if not login_to_linkedin(page, LINKEDIN_EMAIL, LINKEDIN_PASSWORD):
                    logging.error("Failed to login")
                    browser.close()
                    return

                logging.info("Successfully logged in to LinkedIn")

                while True:
                    try:
                        logging.info(f"\n[{datetime.now()}] Checking for new LinkedIn activity...")
                        random_mouse_move(page)
                        check_new_messages(page)
                        human_like_delay(500, 1000)
                        check_new_notifications(page)
                        human_like_delay(500, 1000)
                        logging.info(f"Sleeping for {POLL_INTERVAL} seconds...")
                        time.sleep(POLL_INTERVAL)

                    except KeyboardInterrupt:
                        logging.info("Watcher stopped by user")
                        break
                    except Exception as e:
                        logging.error(f"Error in polling loop: {e}")
                        time.sleep(POLL_INTERVAL)
                        continue

                browser.close()
                break

        except Exception as e:
            logging.error(f"Attempt {retries + 1} failed: {e}")
            retries += 1
            if retries < MAX_RETRIES:
                logging.info("Retrying in 10 seconds...")
                time.sleep(10)
            else:
                logging.error("Max retries reached. Exiting.")
                raise


def run_poster(content):
    """Run the LinkedIn poster"""
    logging.info(f"Posting to LinkedIn: {content[:50]}...")

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=HEADLESS,
                args=[
                    '--disable-blink-features=AutomationControlled',
                    '--disable-dev-shm-usage',
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ]
            )

            context = browser.new_context(
                storage_state=USER_DATA_DIR + "/storage_state.json" if os.path.exists(USER_DATA_DIR + "/storage_state.json") else None
            )
            page = context.new_page()

            if not login_to_linkedin(page, LINKEDIN_EMAIL, LINKEDIN_PASSWORD):
                logging.error("Failed to login")
                browser.close()
                return False

            success = create_post(page, content)
            context.storage_state(path=USER_DATA_DIR + "/storage_state.json")
            browser.close()

            if success:
                logging.info("LinkedIn post completed successfully!")
                return True
            else:
                logging.error("LinkedIn post failed")
                return False

    except Exception as e:
        logging.error(f"Error posting to LinkedIn: {e}")
        return False


def run_both(content=None):
    """Run both watcher and poster"""
    logging.info("Running both watcher and poster...")

    if content:
        logging.info("First, posting content...")
        run_poster(content)

    logging.info("Now starting watcher...")
    run_watcher()


def main():
    """Main entry point for LinkedIn Manager."""
    parser = argparse.ArgumentParser(description='LinkedIn Manager - Post and Watch')
    parser.add_argument('action', choices=['post', 'watch', 'both'], help='Action to perform')
    parser.add_argument('-c', '--content', type=str, help='Post content (for post/both actions)')
    parser.add_argument('-f', '--file', type=str, help='File containing post content')
    parser.add_argument('--visible', action='store_true', help='Show browser window')

    args = parser.parse_args()

    global HEADLESS
    if args.visible:
        HEADLESS = False

    # Get content if needed
    content = None
    if args.action in ['post', 'both']:
        if args.content:
            content = args.content
        elif args.file:
            try:
                with open(args.file, 'r', encoding='utf-8') as f:
                    content = f.read().strip()
            except Exception as e:
                logging.error(f"Error reading file: {e}")
                sys.exit(1)
        else:
            print("Enter your LinkedIn post content (type 'END' on a new line to finish):")
            lines = []
            while True:
                line = input()
                if line == 'END':
                    break
                lines.append(line)
            content = '\n'.join(lines)

        if not content or not content.strip():
            logging.error("No content provided")
            sys.exit(1)

    print(f"\nLinkedIn Manager - Action: {args.action}\n")

    try:
        if args.action == 'post':
            success = run_poster(content)
            if success:
                print("\n✓ Post published successfully!")
            else:
                print("\n✗ Post failed. Check logs for details.")
                sys.exit(1)

        elif args.action == 'watch':
            print("Starting LinkedIn Watcher... Press Ctrl+C to stop.\n")
            run_watcher()

        elif args.action == 'both':
            run_both(content)

    except KeyboardInterrupt:
        print("\nStopped by user")
    except Exception as e:
        print(f"\nError: {e}")
        logging.error(f"Fatal error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
